on: [push]
name: Publish Docs

jobs:
  build:
    name: Sphinx Pages
    runs-on: ubuntu-latest
    steps:
      - uses: seanzhengw/sphinx-pages@master
        id: sphinx-pages
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          create_readme: true
