on: [push]

name: Publish Docs

jobs:
  build:
    name: Build & Publish Docs
    runs-on: ubuntu-latest
    if: github.repository == 'royerlab/dexp'
    steps:
      - name: Commit documentation changes
        run: |
          git clone https://github.com/royerlab/dexp.git
          cd dexp
          ls -l docs/build/html/
          cp -r docs/build/html/ gh-pages/
          cd gh-pages
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          git add .
          git commit -m "Update documentation" -a || true
          # The above command will fail if no changes were present, so we ignore
          # the return code.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          directory: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}