on: [push]

name: Publish Docs

jobs:
  build:
    name: Build & Publish Docs
    runs-on: ubuntu-latest
    if: github.repository == 'royerlab/dexp'
    steps:
      - name: Commit documentation changes
        run: |
          rm -rf gh-pages
          mkdir gh-pages
          git clone https://github.com/royerlab/dexp.git
          cd dexp/docs/
          ls
          make clean
          make html
          cp -r build/html/* ../../gh-pages/.
          git fetch origin
          git checkout gh-pages
          git config --local user.email "action@github.com"
          git config --local user.name "GitHub Action"
          cp -rf ../gh-pages/* .
          git add .
          git commit -m "Update documentation" -a || true
          # The above command will fail if no changes were present, so we ignore
          # the return code.
      - name: Push changes
        uses: ad-m/github-push-action@master
        with:
          branch: gh-pages
          github_token: ${{ secrets.GITHUB_TOKEN }}